- name: Set wheel_user variable based on OS
  ansible.builtin.set_fact:
    wheel_user: "{{ 'wheel' if ansible_os_family == 'RedHat' else 'sudo' }}"
  when:
    - ansible_os_family in ['RedHat', 'Debian']

- name: "Create user"
  ansible.builtin.include_tasks: create_user.yaml
  loop: "{{ ssh_users }}"
  loop_control:
    loop_var: user
  when: ssh_users is defined


- name: Remove absent users
  ansible.builtin.include_tasks: delete_users.yaml
  loop: "{{ delete_users }}"
  loop_control:
    loop_var: user
  when: delete_users is defined
